const express = require('express')
const cors = require('cors')
const app = express()
const PORT = process.env.PORT || 3500
require('dotenv').config()

app.use(cors())
app.use(express.json())

const connectToDB = require('./config/dbConfig')

const eventRouter = require('./routes/eventRouter')
const floorRouter = require('./routes/floorRouter.js')
const groupChannelRouter = require('./routes/groupChannelRouter.js')
const groupChatRouter = require('./routes/groupChatRouter.js')
const guestRouter = require('./routes/guestRouter.js')
const hostRouter = require('./routes/hostRouter.js')
const imageChannelRouter = require('./routes/imageChannelRouter.js')
const imageRouter = require('./routes/imageRouter.js')
const imageUploadRouter = require('./routes/imageUploadRouter.js')
const meetingRouter = require('./routes/meetingRouter.js')
const paymentRouter = require('./routes/paymentRouter.js')
const rsvpRouter = require('./routes/rsvpRouter.js')
const subEventRouter = require('./routes/subEventRouter.js')
const userRouter = require('./routes/userRouter.js')
const vendorRouter = require('./routes/vendorRouter.js')
const venueRouter = require('./routes/venueRouter.js')

app.use('/event', eventRouter)
app.use('/floor', floorRouter)
app.use('/group-channel', groupChannelRouter)
app.use('/group-chat', groupChatRouter)
app.use('/guest', guestRouter)
app.use('/host', hostRouter)
app.use('/image-channel', imageChannelRouter)
app.use('/image', imageRouter)
app.use('/image-upload', imageUploadRouter)
app.use('/meeting', meetingRouter)
app.use('/payment', paymentRouter)
app.use('/rsvp', rsvpRouter)
app.use('/subEvent', subEventRouter)
app.use('/user', userRouter)
app.use('/vendor', vendorRouter)
app.use('/venue', venueRouter)

connectToDB()

app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`)
})