name: Expo App Build

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Install dependencies
      working-directory: ./client
      run: npm install

    - name: Build Expo app
      working-directory: ./client
      run: expo build:android --non-interactive

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-build
        path: client/android/app/build/outputs/apk/release/app-release.apk
